---
title: "Instructions"
output: html_document
---


## Instructions
***

### **Inputs:**



1. There is only one catch option available to choose from:
  1. F<sub>MSY</sub> × SSB<sub>2021</sub> / MSY B<sub>trigger</sub>
2. Select the time step to be used in the allocation simulation.
3. Select the management options to be applied to the recreational component (default options are the current management measures in place).
4. Input vessel catch allocation by gears in the table (in tonnes per vessel).
5. Click `Run simulation` to test the allocations.


<br>

Every time a change is made to any of the inputs the simulation needs to be run again by pressing `Run Simulation`

<br>

### **Outputs:**


On the top right is shown a plot of catch-at-age in thousands by gear. The black dashed line is the catch-at-age for the advice given in the main ICES advice for this stock.

<br>

Below the plot, a table is shown with the results of the simulation. Since the catch allocations are not allowed to exceed the ICES advice (ICES, 2021a), final catch allocations may be less than those initially entered. For monthly simulations, the initial catch allocations are taken each month until the advice value is reached. For subsequent months the catch is set to zero.

<br>

The final table shows the summary of the forecast, including the impact in the SSB and the change in advice. The table compares the simulated catch allocations with the forecast scenarios from the ICES advice.

<br>
<br>


### **New features added in 2020:**

-	Table added indicating the number of vessels by gear used in the tool to raise the catch allocations. A document (ICES, 2020) with an analysis on how the vessels numbers were derived is available in the useful links tab.
-	Improved input table functionality:
  - It is now possible to copy and paste directly to and from excel
  - If the user decides to change allocations by year to allocations by month, the yearly allocations entered will be split throughout the months, making it easier to fill in the monthly table.

- Table 3 can be copied, printed or downloaded.
- Figure 1 is now interactive, among other functionalities, it is now possible to hover the mouse pointer over the figure to check values, either one at the time or for all the gears at the same time.
<br>
<br>


### **Notes:**
***

The total catch available for the commercial gears is the ICES advice minus the expected recreational catch.


The simulation estimates the catch-at-age that will lead to the tonnage specified for each gear, based on an analysis of the selectivity of each gear. As such, it may not be possible to catch the exact tonnage entered, and resulting values may differ by a few tonnes. The outputs are values rounded to the nearest tonne.

<br>

Discard proportions by gear (amount of the catch that is discarded) have been estimated using French and UK data from 2016 to 2018 (ICES, 2019). Current data are insufficient to accurately estimate discard selectivity by gear type, so the same discard selectivity as used in the ICES forecast is applied for all gears. Depending on the allocations by gear, the total amount of discards may vary from that forecasted in the ICES advice.

The gear aggregation used in input catch allocation table are the ones specified in article 10 of EU, 2020.

<br>
<br>

### **References:**
***

ICES. 2019. Working Group for the Celtic Seas Ecoregion (WGCSE). ICES Scientific Reports. 1:29. 1587 pp. http://doi.org/10.17895/ices.pub.4982

ICES.2020. Brief analysis of the data received in response to the 2020 data call on landings by vessel and métier for sea bass (*Dicentrarchus labrax*) in divisions 4.b–c, 7.a, and 7.d–h. In Report of the ICES Advisory Committee, 2020. ICES Advice 2020, ts.2020.01. https://doi.org/10.17895/ices.advice.7511. The associated online sea bass catch allocation tool can be accessed at https://doi.org/10.17895/ices.data.7512.

ICES.2021a. Sea  bass(*Dicentrarchus  labrax*)  in  divisions 4.b–c,7.a,  and 7.d–h (central  and southern  North  Sea,  Irish  Sea,  English Channel,  Bristol  Channel,  and  Celtic  Sea. In Report of the ICES Advisory Committee, 2021. ICES Advice 2021, bss.27.4bc7ad-h. https://doi.org/10.17895/ices.advice.7733

EU.2020. Council Regulation (EU) 2020/123 of 27 January 2020 fixing for 2020 the fishing opportunities for certain fish stocks and groups of fish stocks, applicable in Union waters and, for Union fishing vessels, in certain non-Union waters.ST/15319/2019/INIT. Official Journal of the European Union L25, 30.1.2020, p. 1–156 http://data.europa.eu/eli/reg/2020/123/oj


<br>
<br>


This tool has gone through extensive debugging and error checking. Nevertheless, if you encounter any inconsistency or bug please let us know by emailing us at accessions@ices.dk
<br>
<br>
